### ISSUE TITLE
Enable Organization Runners

### ISSUE THREAD

**Issue by jeanschmidt** [pytorch/multipy#134]

**Comment by d4l3k** [comment]
@jeanschmidt can you share more context on this?

**Comment by jeanschmidt** [comment]
Yes, I don't know if you have access to the internal communication channels, but this issue, while open, controls at witch level the GHA self-hosted runners will run: repo-only or org-wide.

This is done as we think that if there is a SEV with GHA self-runners due to the migration, we can disable it quickly
