### ISSUE TITLE
What versions of Python are supported?

### ISSUE THREAD

**Issue by ezyang** [pytorch/multipy#213]
On a 3.7 conda install, it spins forever in `conda install -c conda-forge libpython-static=3.7`

**Comment by d4l3k** [comment]
Can't comment specifically on why conda is hanging forever but conda doesn't have libpython-static=3.7.

From the README:

> NOTE We support Python versions 3.7 through 3.10 for multipy; note that for conda environments the libpython-static libraries are available for 3.8 onwards. With virtualenv/pyenv any version from 3.7 through 3.10 can be used, as the PIC library is built explicitly.

LMK if there's any way we can make it clearer

https://github.com/pytorch/multipy#installing-environment-encapsulators
