### ISSUE TITLE
Single command to build from source

### ISSUE THREAD

**Issue by ezyang** [pytorch/multipy#214]
PyTorch lets you setup both Python and C++ bits using `python setup.py develop`; it would be great if multipy supported the same.

**Comment by d4l3k** [comment]
Just tested it locally and it is supported (though we had a small regression picking python versions which is fixed in https://github.com/pytorch/multipy/pull/218)

Is it not working for you?

cc @anirbanr-fb-r2p

**Comment by ezyang** [comment]
I didn't try because the docs didn't say this would work lol

**Comment by anirbanr-fb-r2p** [comment]
Yes we have a single source build command : `pip install -e .` , which is essentially `setup.py develop` which in turn calls `cmake` for the c++ extensions. For a cmake-free build one can run `pip install -e . --install-option="--cmakeoff"`.
