### ISSUE TITLE
libpython_multipy.a: error adding symbols: File format not recognized

### ISSUE THREAD

**Issue by ezyang** [pytorch/multipy#215]
I attempted to build multipy on a Facebook devserver with a Conda install and it fails to build at link time with

```
[ 32%] Linking CXX shared library libtorch_deployinterpreter.so
/usr/bin/ld: libpython_multipy.a(abstract.o): unable to initialize decompress status for section .debug_info
/usr/bin/ld: libpython_multipy.a(abstract.o): unable to initialize decompress status for section .debug_info
libpython_multipy.a: error adding symbols: File format not recognized
collect2: error: ld returned 1 exit status
```

Should be reproducible by FB employees.

**Comment by d4l3k** [comment]
Closed by https://github.com/pytorch/multipy/commit/8c7e487e4bdd9a5490ba4eda3827ec31154fb34b 

Older binutils can't handle python in conda built by newer binutils so we have to strip the debug info
