### ISSUE TITLE
Question: is there any multi-threading inference example?

### ISSUE THREAD

**Issue by KexinFeng** [pytorch/multipy#297]
Hi
I have gone through the test examples but didn't find any multi-threading inference example. Maybe I missed it. Could you point such examples to me? 

Or, is the experiment code for Fig.5 in this [paper](https://arxiv.org/pdf/2104.00254.pdf) shared anywhere? If so could you point it to me too?

Thanks

**Comment by PaliC** [comment]
Sorry for the late reply. 

We have two examples of multithreading. The first is in our test case https://github.com/pytorch/multipy/blob/19617b95252c97547e17d598c0b2cb03d0f4e936/multipy/runtime/test_deploy.cpp#L163

The second is our benchmarking (though its a bit changed from whats used in the paper) https://github.com/pytorch/multipy/blob/main/multipy/runtime/example/benchmark.cpp
