### ISSUE TITLE
Using `make install` to pack nigthly tarball?

### ISSUE THREAD

**Issue by reyoung** [pytorch/multipy#76]
`multipy` nightly tarball is packed by copying `cmake` build directory.

https://github.com/pytorch/multipy/blob/29b778e6cf7cd8764d55683a4bc690943fac594c/.github/workflows/runtime_nightly.yaml#L105-L106

It is a bit hacky and does not contain `multipy/runtime` prefix in this tarball. 

Is it better to use `make install` to pack nightly tarball?

**Comment by PaliC** [comment]
To be consistent with the rest of pytorch, it's probably best to not install directly to the path. However, we fixed up the path https://github.com/pytorch/multipy/pull/79

**Comment by PaliC** [comment]
Resolved by https://github.com/pytorch/multipy/pull/79
