### ISSUE TITLE
Fail to load package contains huggingface transformer in Torch::Deploy

### ISSUE THREAD

**Issue by JiayiFeng** [pytorch/multipy#82]
I try to dump a model contains huggingface transformer into a package and then load it in Torch::Deploy. During dumping, everything is OK, while loading it in Torch::Deploy it crashes and throws following error message:

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Exception Caught inside torch::deploy embedded library:
Exception Caught inside torch::deploy embedded library:
ModuleNotFoundError: No module named 'torch._C._nn'; 'torch._C' is not a package

At:
  <Generated by torch::deploy>(436): _do_find_and_load
  <Generated by torch::deploy>(448): _find_and_load
  <Generated by torch::deploy>(478): _gcd_import
  <Generated by torch::deploy>(148): import_module
  <Generated by torch::deploy>(25): find_class
  <Generated by torch::deploy>(1526): load_global
  <Generated by torch::deploy>(1212): load
  <Generated by torch::deploy>(270): load_pickle

Aborted (core dumped)
```

Here is my model's definition, only contains a huggingface tokenizer and a BERT model.

```python
# file name: bert_model.py

import torch
from transformers import BertTokenizer, BertModel

class MyBertModel(torch.nn.Module):
    def __init__(self) -> None:
        super().__init__()
        self._tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
        self._model = BertModel.from_pretrained("bert-base-uncased")

    def forward(self, x):
        encoded_input = self._tokenizer(x, return_tensors='pt')
        return self._model(**encoded_input)
```

Here is how I dump this model with torch package:

```python
from torch.package import PackageExporter
from bert_model import MyBertModel

model = MyBertModel()

# Package and export it.
with PackageExporter("bert_package.pt") as e:
    e.intern('bert_model')
    e.extern("sys")
    e.extern("transformers")
    e.save_pickle("model", "model.pkl", model)
```

The package is loaded in the way showed in the demo: https://pytorch.org/docs/1.12/deploy.html#loading-and-running-the-model-in-c

Can anyone helps? Many thanks!

**Comment by d4l3k** [comment]
I believe this is the same issue as #44 . cc @PaliC

**Comment by JiayiFeng** [comment]
Thanks @d4l3k . Is there any plan to fix this bug? It may not be quite convenient for us to change the model itself, especially when it is implemented by someone else.

**Comment by d4l3k** [comment]
Yes, we're planning on fixing it but it's been in the backlog since only one person had run into it. I'll make sure this gets fixed promptly

**Comment by PaliC** [comment]
This issue should be addressed by https://github.com/pytorch/multipy/pull/91 and https://github.com/pytorch/pytorch/pull/80917
